
CREATE TABLE Membresia(
    ID_Membresia Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nombre varchar(50),
    Precio number,
    PRIMARY KEY (ID_Membresia)
    );

    
CREATE TABLE Deporte(
    ID_Deporte Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nombre varchar(50),
    Color varchar(50),
    PRIMARY KEY (ID_Deporte)
);

CREATE TABLE Usuario(
    ID_Usuario Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nombre varchar(50),
    Apellido varchar(50),
    Correo varchar(50),
    Username varchar(50),
    Fecha_Nacimiento Date,
    Fecha_Registro TIMESTAMP,
    Foto blob,
    PRIMARY KEY (ID_Usuario)
);

CREATE TABLE Temporada(
    ID_Temporada Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Fecha_Inicio Date,
    Fecha_Final Date,
    Nombre varchar(50),
    PRIMARY KEY (ID_Temporada)
);

CREATE TABLE Fase(
    ID_Fase Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nombre varchar(50),
    PRIMARY KEY (ID_Fase)
);

CREATE TABLE Equipo(
    ID_Equipo Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nombre varchar(50),
    PRIMARY KEY (ID_Equipo)
);

CREATE TABLE Jornada(
    ID_Jornada Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Fecha_Inicio Date,
    Fecha_Fin Date,
    ID_Temporada,
    PRIMARY KEY (ID_Jornada),
    FOREIGN KEY (ID_Temporada) REFERENCES Temporada(ID_Temporada)
);

CREATE TABLE Jornada_Fase(
    ID_Jornada_Fase Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_Jornada number,
    ID_Fase number,
    Fecha Date,
    PRIMARY KEY (ID_Jornada_Fase),
    FOREIGN KEY (ID_Jornada) REFERENCES Jornada(ID_Jornada),
    FOREIGN KEY (ID_Fase) REFERENCES Fase(ID_Fase)
);



CREATE TABLE Usuario_Membresia(
    ID_Usuario_Membresia Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_Usuario number,
    ID_Membresia number,
    PRIMARY KEY (ID_Usuario_Membresia),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Membresia) REFERENCES Usuario(ID_Usuario)
);

CREATE TABLE Puntaje(
    ID_Puntaje Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_Usuario number,
    ID_Temporada number,
    PRIMARY KEY (ID_Puntaje),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Temporada) REFERENCES Temporada(ID_Temporada)
);


CREATE TABLE Evento(
    ID_Evento Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_Deporte number,
    ID_Equipo_Visitante number,
    ID_Equipo_Local number,
    ID_Jornada number,
    Puntaje_Local number,
    Puntaje_Visitante number,
    PRIMARY KEY (ID_Evento),
    FOREIGN KEY (ID_Deporte) REFERENCES Deporte(ID_Deporte),
    FOREIGN KEY (ID_Equipo_Visitante) REFERENCES Equipo(ID_Equipo),
    FOREIGN KEY (ID_Equipo_Local) REFERENCES Equipo(ID_Equipo),
    FOREIGN KEY (ID_Jornada) REFERENCES Jornada(ID_Jornada)
);

CREATE TABLE Prediccion(
    ID_Prediccion Number GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_Usuario number,
    ID_Evento number,
    Puntaje_Local number,
    PUntaje_Visitante number,
    Fecha TIMESTAMP,
    PRIMARY KEY (ID_Prediccion),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Evento) REFERENCES Evento(ID_Evento)   
);



